"""Compatibility facade for judgment context helpers.

This module keeps the stable import path ``core.judgment.context`` while the
implementation is grouped by topic inside this package.
"""

from __future__ import annotations

from .facts import (
    _FACT_CONTEXT_EXCLUDE_PREFIXES,
    _load_context_facts_snapshot,
    _load_durable_failure_snapshot,
)
from .runtime import (
    _fmt_chat_continuity,
    _fmt_chat_history,
    _fmt_chat_memories,
    _fmt_config_snapshot,
    _fmt_cross_task_episodic,
    _fmt_current_time,
    _fmt_ethos,
    _fmt_hard_boundaries,
    _fmt_interlocutor_continuity,
    _fmt_judgment_signals,
    _fmt_memories,
    _fmt_memory_recall,
    _fmt_memory_system,
    _fmt_percept,
    _fmt_perception_replay,
    _fmt_shell_capabilities,
    _fmt_soul,
    _fmt_tools,
    _fmt_wm,
    apply_context_budget,
)
from .skills import (
    _fmt_blind_spots,
    _fmt_cognitive_signals,
    _fmt_primary_skill,
    _fmt_probe_sensors,
    _fmt_skill_catalog,
    _fmt_skills,
    _short_skill_desc,
)
from .tasks import (
    _fmt_context_facts,
    _fmt_durable_failures,
    _fmt_evolution_breakers,
    _fmt_failures,
    _fmt_recent_runs,
    _fmt_runnable_tasks,
    _fmt_similar_tasks,
    _fmt_task,
    _fmt_waiting_tasks,
    _task_narrative,
)
from .utils import (
    _CONTEXT_SCHEMA_KEYS,
    _MAX_CONTEXT_CACHE_SIZE,
    _cache_put,
    _clear_context_cache,
    _clip_text,
    _compress_single_segment,
    _compress_text_segments,
    _context_fmt_cache,
    _estimate_tokens,
    _fill_template,
    _format_fact_value,
    _run_summary,
    _split_segments,
    _validate_context_schema,
)

__all__ = [
    "_context_fmt_cache",
    "_MAX_CONTEXT_CACHE_SIZE",
    "_cache_put",
    "_clear_context_cache",
    "_task_narrative",
    "_fmt_task",
    "_fmt_recent_runs",
    "_FACT_CONTEXT_EXCLUDE_PREFIXES",
    "_load_context_facts_snapshot",
    "_format_fact_value",
    "_fmt_context_facts",
    "_fmt_evolution_breakers",
    "_fmt_waiting_tasks",
    "_fmt_runnable_tasks",
    "_fmt_similar_tasks",
    "_run_summary",
    "_clip_text",
    "_fmt_current_time",
    "_fmt_chat_history",
    "_fmt_chat_continuity",
    "_fmt_cross_task_episodic",
    "_fmt_interlocutor_continuity",
    "_fmt_chat_memories",
    "_fmt_wm",
    "_fmt_failures",
    "_load_durable_failure_snapshot",
    "_fmt_durable_failures",
    "_fmt_memories",
    "_fmt_memory_recall",
    "_fmt_memory_system",
    "_fmt_tools",
    "_fmt_config_snapshot",
    "_fmt_shell_capabilities",
    "_fmt_percept",
    "_fmt_soul",
    "_fill_template",
    "_fmt_ethos",
    "apply_context_budget",
    "_estimate_tokens",
    "_compress_text_segments",
    "_split_segments",
    "_compress_single_segment",
    "_fmt_judgment_signals",
    "_fmt_hard_boundaries",
    "_fmt_perception_replay",
    "_short_skill_desc",
    "_fmt_skill_catalog",
    "_fmt_primary_skill",
    "_fmt_skills",
    "_fmt_cognitive_signals",
    "_CONTEXT_SCHEMA_KEYS",
    "_validate_context_schema",
    "_fmt_blind_spots",
    "_fmt_probe_sensors",
]
