"""tools/view_protocols.py — 子灵隔离视图的结构化协议（Protocol）。

供 ToolContext / JudgmentLayer.decide() 使用，替换 cast(Any) 类型逃逸。
视图类（_SubagentTaskStoreView 等）和真实存储类（TaskStore 等）均结构上满足这些 Protocol。

公理 A7（子灵授权）：子灵通过隔离视图访问存储，不直接持有父灵 TaskStore 引用。
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class TaskStoreViewProtocol(Protocol):
    """TaskStore 最小结构协议（供 ToolContext / decide() 参数类型约束）。"""

    async def get_fact(self, key: str) -> tuple[Any, bool]: ...
    async def set_fact(self, key: str, value: str, scope: str = "task") -> None: ...
    async def get_active(self) -> Any: ...
    async def get_task_by_id(self, task_id: int) -> Any: ...
    async def list_tasks(self, status: str | None = None, limit: int = 50) -> list[Any]: ...
    async def list_runnable_tasks(self, limit: int = 20) -> list[Any]: ...
    async def list_runs(self, task_id: int | None = None, status: str | None = None, limit: int = 50) -> list[Any]: ...
    async def list_failures(self, limit: int = 20) -> list[Any]: ...
    async def list_failures_for_task(self, task_id: str, limit: int = 20) -> list[Any]: ...


@runtime_checkable
class EpisodicViewProtocol(Protocol):
    """EpisodicMemory 最小结构协议。"""

    def load_for_context(self, task_id: str | None, *, max_chars: int = 4000) -> str: ...
    def search(self, query: str, max_chars: int = 4000, task_id: str | None = None) -> str: ...
    def get_recent_turns(self, limit: int = 20) -> list[dict[str, Any]]: ...
    def list_recent_narrative(self, limit: int = 20) -> list[dict[str, Any]]: ...


@runtime_checkable
class SemanticViewProtocol(Protocol):
    """SemanticMemory 最小结构协议。"""

    def retrieve(self, query: str, **kwargs: Any) -> list[dict[str, Any]]: ...
    def retrieve_multi_anchor(self, anchors: list[str], **kwargs: Any) -> list[dict[str, Any]]: ...
    def upsert(self, node: Any) -> None: ...
    def stats(self) -> dict[str, Any]: ...
